"""create stores tables

Revision ID: 9aad094b44d3
Revises: 20260719_0008
Create Date: 2026-07-22 10:50:24.484162
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9aad094b44d3'
down_revision: Union[str, None] = '20260719_0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'verified', 'published', 'suspended', name='store_status'), server_default='draft', nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trust_score', sa.Integer(), server_default='50', nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_stores_slug')
    )
    op.create_index(op.f('ix_stores_active'), 'stores', ['active'], unique=False)
    op.create_index(op.f('ix_stores_category_id'), 'stores', ['category_id'], unique=False)
    op.create_index(op.f('ix_stores_city_id'), 'stores', ['city_id'], unique=False)
    op.create_index(op.f('ix_stores_country_id'), 'stores', ['country_id'], unique=False)
    op.create_index(op.f('ix_stores_owner_id'), 'stores', ['owner_id'], unique=False)
    op.create_index(op.f('ix_stores_slug'), 'stores', ['slug'], unique=True)
    op.create_index(op.f('ix_stores_status'), 'stores', ['status'], unique=False)
    op.create_index(op.f('ix_stores_store_name'), 'stores', ['store_name'], unique=False)
    op.create_table('store_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='store_document_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_documents_status'), 'store_documents', ['status'], unique=False)
    op.create_index(op.f('ix_store_documents_store_id'), 'store_documents', ['store_id'], unique=False)
    op.create_table('store_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.String(length=5), nullable=True),
    sa.Column('closes_at', sa.String(length=5), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'day_of_week', name='uq_store_hours_store_day')
    )
    op.create_index(op.f('ix_store_hours_store_id'), 'store_hours', ['store_id'], unique=False)
    op.create_table('store_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('image_type', sa.Enum('logo', 'cover', 'gallery', name='store_image_type'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_images_image_type'), 'store_images', ['image_type'], unique=False)
    op.create_index(op.f('ix_store_images_store_id'), 'store_images', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_images_store_id'), table_name='store_images')
    op.drop_index(op.f('ix_store_images_image_type'), table_name='store_images')
    op.drop_table('store_images')
    op.drop_index(op.f('ix_store_hours_store_id'), table_name='store_hours')
    op.drop_table('store_hours')
    op.drop_index(op.f('ix_store_documents_store_id'), table_name='store_documents')
    op.drop_index(op.f('ix_store_documents_status'), table_name='store_documents')
    op.drop_table('store_documents')
    op.drop_index(op.f('ix_stores_store_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_status'), table_name='stores')
    op.drop_index(op.f('ix_stores_slug'), table_name='stores')
    op.drop_index(op.f('ix_stores_owner_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_country_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_city_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_category_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_active'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
